<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'Fidelo\\Fidelo\\' => array($typo3InstallDir . 'typo3conf/ext/fidelo/Classes'),
    'GeorgRinger\\News\\' => array($typo3InstallDir . 'typo3conf/ext/news/Classes'),
    'Joppnet\\JnPhpcontentelement\\' => array($typo3InstallDir . 'typo3conf/ext/jn_phpcontentelement/Classes'),
    'Mahir\\NewsPortal\\' => array($typo3InstallDir . 'typo3conf/ext/news_portal/Classes'),
);
